import json
from agents.state import AgentState, MISSING, PENDING


# ─────────────────────────────────────────────
# SAFETY GUARDRAIL NODE
# ─────────────────────────────────────────────

def safety_guardrail_node(state: AgentState) -> AgentState:
    """
    Final safety check before output is generated.
    Rules:
    - Every empty or None field → replaced with MISSING
    - Every field that was guessed or inferred without source → flagged
    - Conflicts still unresolved → flagged
    - Unexplained med changes still present → flagged
    - Never removes flags — only adds
    - This node never calls an LLM — pure deterministic logic only
    """

    state.trace.append({
        "step": state.step_count,
        "node": "safety_guardrail",
        "action": "running safety checks — no fabrication enforcement",
    })

    print(f"[SAFETY GUARDRAIL] Running safety checks...")

    summary = state.summary
    issues_found = 0

    # ── 1. Check all string fields for None or empty ──
    string_fields = [
        "patient_name", "patient_id", "age_sex", "dob",
        "admission_date", "discharge_date", "consultant", "ward",
        "principal_diagnosis", "hospital_course",
        "allergies", "discharge_condition"
    ]

    for field in string_fields:
        value = getattr(summary, field, None)
        if not value or value.strip() == "":
            setattr(summary, field, MISSING)
            flag = f"MISSING FIELD - '{field}' could not be extracted — Clinician Review Required"
            summary.flags.append(flag)
            print(f"[SAFETY GUARDRAIL] ⚠ {flag}")
            issues_found += 1

    # ── 2. Check list fields for empty ──
    if not summary.secondary_diagnoses:
        summary.flags.append(
            "INFO - No secondary diagnoses found — verify with clinician"
        )

    if not summary.procedures:
        summary.flags.append(
            "INFO - No procedures recorded — verify with clinician"
        )

    if not summary.follow_up_instructions:
        summary.flags.append(
            "MISSING FIELD - 'follow_up_instructions' not found — Clinician Review Required"
        )
        issues_found += 1

    # ── 3. Check medications ──
    if not summary.admission_medications:
        flag = "MISSING FIELD - Admission medications not found — Clinician Review Required"
        summary.flags.append(flag)
        print(f"[SAFETY GUARDRAIL] ⚠ {flag}")
        issues_found += 1

    if not summary.discharge_medications:
        flag = "MISSING FIELD - Discharge medications not found — Clinician Review Required"
        summary.flags.append(flag)
        print(f"[SAFETY GUARDRAIL] ⚠ {flag}")
        issues_found += 1

    # ── 4. Check for unresolved conflicts ──
    if summary.conflicts:
        flag = (
            f"UNRESOLVED CONFLICTS - {len(summary.conflicts)} conflict(s) "
            f"detected and unresolved — Clinician Review Required"
        )
        summary.flags.append(flag)
        print(f"[SAFETY GUARDRAIL] ⚠ {flag}")
        issues_found += 1

    # ── 5. Check for unexplained med changes ──
    unexplained = [
        c for c in summary.medication_changes
        if c.change_type in ("stopped", "dose_changed", "unexplained")
    ]
    if unexplained:
        flag = (
            f"UNEXPLAINED MED CHANGES - {len(unexplained)} change(s) "
            f"require clinician review before discharge"
        )
        summary.flags.append(flag)
        print(f"[SAFETY GUARDRAIL] ⚠ {flag}")
        issues_found += 1

    # ── 6. Check allergies specifically — critical safety field ──
    if summary.allergies == MISSING:
        flag = "CRITICAL - Allergy status unknown — DO NOT discharge without verification"
        summary.flags.append(flag)
        print(f"[SAFETY GUARDRAIL] 🚨 {flag}")
        issues_found += 1

    # ── 7. Add final disclaimer to summary ──
    summary.flags.append(
        "DRAFT ONLY - This discharge summary was generated by an AI agent "
        "and must be reviewed and approved by a qualified clinician before use."
    )

    print(f"[SAFETY GUARDRAIL] ✓ Safety check complete — {issues_found} issue(s) flagged")

    state.trace.append({
        "step": state.step_count,
        "node": "safety_guardrail",
        "result": f"{issues_found} issue(s) flagged",
        "total_flags": len(summary.flags)
    })

    # Advance plan
    state = _advance_plan(state)
    state.step_count += 1
    return state


# ─────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────

def _advance_plan(state: AgentState) -> AgentState:
    if state.plan:
        state.plan.pop(0)
    state.current_task = state.plan[0] if state.plan else "format_output"
    return state